debuggerd: Resolve tombstoned missing O_CREAT mode
 debuggerd/tombstoned/tombstoned.cpp:115:92:
  error: 'openat' has superfluous mode bits; missing O_CREAT?
    unique_fd result(openat(dir_fd_, ".",
    O_WRONLY | O_APPEND | O_TMPFILE | O_CLOEXEC, 0640));

Change-Id: Iae787e477b7eab1f11c79f30c35fd6808959e38a

Former-commit-id: 15c145fb30f02aedd3bbade924d5b1f9da52d113
Former-commit-id: 715b2516f0ca20206b912756cb112acbed8c3485
Former-commit-id: 6d86053bce2d2c4d15ded63da06f1d8fe411b6c0